services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile 
    container_name: rag_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./indices:/app/indices
    restart: always

  frontend:
    build: ./frontend
    container_name: rag_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
